In [1]:
import tweepy
import configparser
import pandas as pd
import numpy

from googletrans import Translator
import pandas as pd

# Load data

In [2]:
tweets_dataset = pd.read_csv('tweets_8th_Nov_23_48.csv')

In [310]:
tweets_dataset.head()

,Unnamed: 0,text,created_at,tweet_id,user_id,user_name,user_location,user_description,language
0,0,RT @BhiwaniJunction: @RailMinIndia @drm_dli @R...,2022-11-07 03:18:22+00:00,1589457201852448768,1534550088860594176,Shivkant Sharma,"New Delhi, India",Financial Markets from 2005. Working with @smc...,NaN
1,1,RT @er_rameshwer: जब रेल्वे सप्ताह भर में 1.45...,2022-11-07 03:18:17+00:00,1589457180226629635,2691565863,Jay Kumar,"Bihar, India",NaN,NaN
2,2,Train 04652 Asr Jyg clone special is late more...,2022-11-07 03:18:08+00:00,1589457145392926720,1292824537638170625,Murendra Chaudhary,NaN,NaN,NaN
3,3,RT @metrorailwaykol: Cleanliness campaign at d...,2022-11-07 03:18:00+00:00,1589457110123048960,752751553006735360,RPF POST CENTRAL,RITES Building Central,NaN,NaN
4,4,@tourismgoi @RailMinIndia @Central_Railway \nT...,2022-11-07 03:17:57+00:00,1589457095900147713,195293308,VAIBHAV JAIN,"Bengaluru, India",Chalta Firta Engineer\n#chai \n#pottersir (sir...,NaN

In [283]:
set(tweets_dataset.language) # Language field is not filled

set(tweets_dataset.user_location)

{' India',
 ' Pratapgarh, India',
 'Alambagh, Lucknow',
 'Alamnagar, Lucknow, India',
 'Allahabad, India',
 'Alwar, India',
 'Amethi, India',
 'Amravati, India',
 'Anupshahr, India',
 'Aurangabad bihar',
 'Bahrain',
 'Ballabgarh, Faridabad',
 'Ballia UP India',
 'Ballia, India',
 'Bangalore',
 'Bangalore, Nellore',
 'Bardhaman, India',
 'Basti, Uttar Pradesh',
 'Baswa, India',
 'Bengaluru ',
 'Bengaluru, India',
 'Bettahalsur, Dodjala railway s',
 'Bhopal',
 'Bhubaneswar',
 'Bihar Sharif, India',
 'Bihar, India',
 'Bikaner, Rajasthan',
 'Bilaspur, Chhattisgarh',
 'Bilaspur, India',
 'Blue City, Jodhpur',
 'Chennai',
 'Chennai, India',
 'Cherai-Osian-Jodhpur 342306',
 'Delhi',
 'Deoria, India',
 'Diamond Harbour, West Bengal',
 'Freebie Land',
 'Gangarampur, India',
 'Gaya',
 'Ghaziabad, India',
 'Ghazipur, India',
 'Gonda, India',
 'Gorakhpur, India',
 'Greater Noida, India',
 'Gujarat, India',
 'Guwahati, India',
 'Hamirpur HP Amritsar Punjab',
 'Hayathnagar, India',
 'Hodal, India Haryana',
 'Howrah',
 'Howrah, West Bengal, India',
 'Hyderabad, India',
 'Hyderabad, Telangana',
 'India',
 'India.',
 'Jaipur',
 'Jaipur, India',
 'Jaisalmer Railway Station, Jai',
 'Jalor, India',
 'Jamshedpur, India',
 'Jaunpur Uttar Pradesh India',
 'Jharkhand, India',
 'Jodhpur, India',
 'KOLKATA',
 'Kanpur, India',
 'Katihar, India',
 'Katni',
 'Kerala, India',
 'Koderma/Patna',
 'Kolkata ',
 'Kolkata, India',
 'LKO ',
 'Lucknow',
 'Lucknow, India',
 'MADURAI ,INDIA ',
 'MEDTA CITY',
 'MUMBAI ',
 'Madhya Pradesh, India',
 'Moradabad, India',
 'Mumbai',
 'Mumbai, India',
 'Nagaur, India',
 'Nagpur, India',
 'New Coochbehar',
 'New Delhi',
 'New Delhi, Delhi',
 'New Delhi, India',
 'New Delhi, India ',
 'Noida',
 'Noida, India',
 'Panipat',
 'Patna City Outer, India',
 'Patna, India',
 'Pondicherry, India',
 'Prayagraj , India',
 'Prayagraj, India',
 'Pune, India',
 'RITES Building Central',
 'Raebareli',
 'Raipur, India',
 'Rajasthan, India',
 'Rendhar',
 'Rewa, India',
 'Ridkhala Churu, India',
 'Saharanpur Mobile 9759334500',
 'Sainthia,West Bengal,India',
 'Samastipur, India',
 'Surat, India',
 'Swaroop Nagar, Kanpur',
 'Thane, India',
 'Tinsukia',
 'Toronto, Ontario',
 'Tundla',
 'Unnao, India',
 'Uttar Pradesh, India',
 'VARANASI',
 'Varanasi, India',
 'Vidhyavihar',
 'Vododara, India',
 'Wadsa',
 'West Bengal, India',
 'West Champaran Bihar',
 'Zafarabad',
 'ayodhya',
 'baigani',
 'bilaspur',
 'chikna',
 'hyderabad',
 'india',
 'jodhpur',
 'madurai india ',
 'muzaffarpur',
 nan,
 'new delhi',
 'patna,india',
 'vadodara',
 'virudhunagar',
 'अयोध्या , उत्तर प्रदेश',
 'आज़मगढ़, भारत',
 'उत्तर प्रदेश, भारत',
 'उन्नाव, भारत',
 'गोरखपुर, उत्तर प्रदेश',
 'गोरखपुर, भारत',
 'झारखंड, भारत',
 'पटना सिटी आउटर, भारत',
 'भिवानी, भारत',
 'मंझिलाडीह बिरनी गिरिडीह झारखंड',
 'मुंबई, भारत. Mumbai, India',
 'राउरकेला औद्योगिक टाउनशिप, भार',
 'रायबरेली उत्तर प्रदेश ',
 'वड़ोदरा, भारत',
 'स्वदेशो भुवनत्रयम् ',
 'हिंदुस्तान🌍',
 'কলকাতা',
 'தமிழகம்',
 'பாரதம்'}

# Separting @ from tweet text

In [8]:
import re

tweets_dataset.text = [ re.sub("rt :",'',x)for x in tweets_dataset.text]
tweets_dataset.text = [ re.sub("\n",' ',x)for x in tweets_dataset.text]
tweets_dataset.text =  [re.sub(' +'," ", x) for x in tweets_dataset.text]
tweets_dataset.text =  [x.lower() for x in tweets_dataset.text]
tweets_dataset.text =  [re.sub("@[A-Za-z0-9_]+","", x) for x in tweets_dataset.text]
tweets_dataset.text =  [re.sub("#[A-Za-z0-9_]+","", x) for x in tweets_dataset.text]
tweets_dataset.text =  [re.sub(r"http\S+","", x) for x in tweets_dataset.text]
tweets_dataset.text =  [re.sub(r"www.\S+","", x) for x in tweets_dataset.text]
tweets_dataset.text =  [re.sub('[()!?]',"", x) for x in tweets_dataset.text]
tweets_dataset.text =  [re.sub('\[.*?\]',"", x) for x in tweets_dataset.text]
tweets_dataset.text =  [re.sub('\[.*?\]',"", x) for x in tweets_dataset.text]

In [9]:
tweets_dataset.text =  [re.sub("[^A-Za-z0-9]"," ", x) for x in tweets_dataset.text]

In [10]:
tweets_dataset.text =  [re.sub(' +'," ", x) for x in tweets_dataset.text]

In [11]:
tweets_dataset.text

0        this is like worst nightmare to travel via thi...
1        worst service by northern railways no indicato...
2        pnr 4759117458 i am not able to find any charg...
3        the picture of bangalore to nanded link expres...
4         sir i want to inform you that train no 05529 ...
                               ...
17995     hi sir indian rail will be never provide good...
17996     train no 12111 12112 amravati mumbai express ...
17997     can someone help me to get water in the compa...
17998     wht blunder is going on for booking the railw...
17999                                  matter notified to
Name: text, Length: 18000, dtype: object

In [61]:
tweets_dataset.text[0].split(" ")

['RT',
 '@BhiwaniJunction:',
 '@RailMinIndia',
 '@drm_dli',
 '@RailwaySeva',
 '',
 'My',
 'relative',
 'Mr',
 'Shailendra',
 'Ranjan',
 'is',
 'travelling',
 'in',
 'Train',
 'no',
 '12229',
 'Coach',
 'B4',
 'seat',
 'no…']

In [12]:
tweets_dataset.to_csv('project_memo2_cleanedv2.csv')